# Generated by Django 6.0.6 on 2026-06-29 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('game_type', models.CharField(choices=[('PH', 'Physical'), ('DI', 'Digital')], max_length=2)),
                ('genre', models.CharField(choices=[('FP', 'First-person shooter'), ('RP', 'Role Playing'), ('PU', 'Puzzle'), ('SP', 'Sport'), ('TA', 'Tactics'), ('AD', 'Adventure'), ('SI', 'Simulation'), ('TT', 'Tabletop')], max_length=2)),
                ('fsk', models.IntegerField(choices=[(0, 'ab 0'), (6, 'ab 6'), (12, 'ab 12'), (16, 'ab 16'), (18, 'ab 18')])),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('operation_system', models.CharField(choices=[('W', 'Windows'), ('L', 'Linux'), ('M', 'Macos'), ('X', 'Xbox'), ('P', 'Playstation')], max_length=1)),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='ComputerGames.game')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_or_down', models.CharField(choices=[('U', 'up'), ('D', 'down')], max_length=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ComputerGames.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
