# Generated by Django 6.0.6 on 2026-06-25 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('genre', models.CharField(choices=[('action', 'Action'), ('adventure', 'Adventure'), ('rpg', 'RPG'), ('strategy', 'Strategy'), ('sports', 'Sports'), ('puzzle', 'Puzzle'), ('simulation', 'Simulation'), ('fps', 'First-Person Shooter'), ('mmorpg', 'Massively Multiplayer Online Role Playing Game'), ('fighter', 'Fighting Game'), ('platfomer', 'Platformer/Jump And Run')], max_length=50)),
                ('fsk', models.IntegerField(choices=[(0, 'ab 0'), (6, 'ab 6'), (12, 'ab 12'), (16, 'ab 16'), (18, 'ab 18')], default=0)),
                ('developer', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
