# Generated by Django 6.0.6 on 2026-06-29 17:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ComputerGames', '0002_review_reviewcomment_alter_vote_comment_reviewvote_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vote',
            new_name='CommentVote',
        ),
    ]
