# Generated by Django 6.0.6 on 2026-06-29 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComputerGames', '0003_rename_vote_commentvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='head',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
