# Generated by Django 6.0.6 on 2026-06-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComputerGames', '0004_review_head'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='head',
        ),
        migrations.AlterField(
            model_name='game',
            name='operation_system',
            field=models.CharField(choices=[('W', 'Windows'), ('L', 'Linux'), ('M', 'Macos'), ('X', 'Xbox'), ('P', 'Playstation')]),
        ),
    ]
