# Generated by Django 6.0.6 on 2026-06-29 19:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComputerGames', '0006_gameimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='owned_games', to=settings.AUTH_USER_MODEL),
        ),
    ]
