# Generated by Django 6.0.6 on 2026-07-01 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ComputerGames', '0008_cart_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
