# Generated by Django 6.0.6 on 2026-07-01 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ComputerGames', '0009_delete_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
