# Generated by Django 6.0.6 on 2026-07-07 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ComputerGames", "0011_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="stars",
            field=models.IntegerField(
                choices=[
                    (1, "1 Star"),
                    (2, "2 Stars"),
                    (3, "3 Stars"),
                    (4, "4 Stars"),
                    (5, "5 Stars"),
                ],
                default=0,
            ),
        ),
    ]
