# Generated by Django 6.0.6 on 2026-07-08 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ComputerGames", "0013_alter_review_stars"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="fsk",
            field=models.IntegerField(
                choices=[
                    (0, "0 and above"),
                    (6, "6 and above"),
                    (12, "12 and above"),
                    (16, "16 and above"),
                    (18, "18 and above"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="operation_system",
            field=models.CharField(
                choices=[
                    ("W", "Windows"),
                    ("L", "Linux"),
                    ("M", "MacOS"),
                    ("X", "Xbox"),
                    ("P", "PlayStation"),
                ]
            ),
        ),
    ]
