# Generated by Django 6.0.6 on 2026-07-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ComputerGames", "0014_alter_game_fsk_alter_game_operation_system"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="hidden",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reviewcomment",
            name="hidden",
            field=models.BooleanField(default=False),
        ),
    ]
